name: Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup FTP Deployment
        uses: lftp/ftp-deploy-action@v1
        with:
          ftp-server: ecom.codebuilderpro.com
          ftp-username: ${{ secrets.FTP_USERNAME }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}

      - name: Install Composer dependencies
        run: composer install
