on:
  push:
    branches:
      - main
name: 🚀 Deploy Website To Cpanel
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ftp.codebuilderpro.com
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}

      - name: Install dependencies
          uses: php-actions/composer@v6
          with:
            php_version: "7.4"
            version: 2.x